### ISSUE TITLE
Can pixel2 be supported?

### ISSUE THREAD

**Issue by yunswj** [ZenX-OS/zenx_updater#16]
I am a user of Mi 8 and have been using your system. It is very powerful and updates frequently. You are too diligent. I recently had a pixel 2 and I found that it has very few flashing packages. I like your system, so Like to ask, can you support it, or do I use your code to compile and transplant it myself?

**Comment by Lokesh773** [comment]
> I am a user of Mi 8 and have been using your system. It is very powerful and updates frequently. You are too diligent. I recently had a pixel 2 and I found that it has very few flashing packages. I like your system, so Like to ask, can you support it, or do I use your code to compile and transplant it myself?

If you have a maintainer ready we would love to support your device :) Contact our telegram support for further info

**Comment by Lokesh773** [comment]
🙏

**Comment by yunswj** [comment]
What does maintainer mean?  I have no experience in compiling ROM, is it responsible for fixing bugs, testing, and answering some questions in the telegram group?  I want to try if I can
